apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paldo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-discovery
            port:
              number: 8761
      - path: /gateway
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8000
      - path: /portfolio-svc
        pathType: Prefix
        backend:
          service:
            name: portfolio-service
            port:
              number: 8001