server:
  port: ${API_GATEWAY_PORT:8000}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SERVICE_DISCORVERY_ADDRESS:localhost}:${SERVICE_DISCORVERY_PORT:8761}/eureka


spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: portfolio-service
          uri: lb://PORTFOLIO-SERVICE
          predicates:
            - Path=/portfolio-service/**
          filters:
            - RewritePath=/portfolio-service/(?<segment>.*), /$\{segment}
        - id: budget-service
          uri: lb://BUDGET-SERVICE
          predicates:
            - Path=/budget-service/**
          filters:
            - RewritePath=/budget-service/(?<segment>.*), /$\{segment}
        - id: subscribe-service
          uri: lb://SUBSCRIBE-SERVICE
          predicates:
            - Path=/subscribe-service/**
          filters:
            - RewritePath=/subscribe-service/(?<segment>.*), /$\{segment}


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh