apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-service
  labels:
    app: portfolio-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-service
  template:
    metadata:
      labels:
        app: portfolio-service
    spec:
      containers:
      - name: portfolio-service
        image: gojeasuk3/portfolio-service:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: PORTFOLIO_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: paldo-config
              key: PORTFOLIO_SERVICE_PORT
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: paldo-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: paldo-config
              key: DB_PORT
        - name: PORTFOLIO_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: paldo-config
              key: PORTFOLIO_DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: paldo-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: paldo-config
              key: DB_PASSWORD
        - name: SERVICE_DISCOVERY_PORT
          valueFrom:
            configMapKeyRef:
              name: paldo-config
              key: SERVICE_DISCOVERY_PORT
