server:
  port: ${PORTFOLIO_SERVICE_PORT:8001}


spring:
  application:
    name: portfolio-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:169.56.174.138}:${DB_PORT:32070}/${PORTFOLIO_DB_NAME:portfolio}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:passw0rd}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: create

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SERVICE_DISCORVERY_ADDRESS:localhost}:${SERVICE_DISCORVERY_PORT:8761}/eureka


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh